version: '3.7'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:ro
    ports:
      - 80:80
  php:
    build:
      context: docker/php
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    command: bash -c "php artisan migrate && php-fpm"
  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
